export default [
    {
        "id": 1,
        "title": "Introduzione a HTML e CSS",
        "image": "/image/images.jpeg",
        "content": "HTML è il linguaggio di markup standard per creare pagine web. È utilizzato per strutturare il contenuto e definire gli elementi della pagina, come testi, immagini e link.",
        "tags": ["html", "css"],
        "published": true,
    },
    {
        "id": 2,
        "title": "CSS: Design e Stile per il Web",
        "image": "/image/html5-javascript.jpg",
        "content": "CSS (Cascading Style Sheets) è utilizzato per definire lo stile visivo delle pagine web. Permette di gestire colori, font, layout e animazioni.",
        "tags": ["html", "js"],
        "published": true,
    },
    {
        "id": 3,
        "title": "PHP: Introduzione al Server-Side Scripting",
        "image": "/image/jsphp.jpeg",
        "content": "PHP è un linguaggio di scripting lato server utilizzato per creare applicazioni web dinamiche. È comunemente usato in combinazione con database come MySQL.",
        "tags": ["js", "php"],
        "published": true,
    },
    {
        "id": 4,
        "title": "JavaScript e la Programmazione Web Interattiva",
        "image": "/image/javascript.png",
        "content": "JavaScript è un linguaggio di programmazione client-side che rende le pagine web interattive. Viene utilizzato per creare effetti dinamici, validazioni dei form e molto altro.",
        "tags": ["js"],
        "published": false,
    },
    {
        "id": 5,
        "title": "PHP e MySQL: Connettere un Database",
        "image": "/image/php.jpg",
        "content": "PHP offre un'ottima integrazione con MySQL per la gestione dei database. In questo articolo, vedremo come connettere un database MySQL e interagire con esso tramite PHP.",
        "tags": ["php"],
        "published": true,
    },
    {
        "id": 6,
        "title": "CSS Flexbox: Layout Moderno per il Web",
        "image": "/image/css.png",
        "content": "Flexbox è un potente strumento in CSS che permette di creare layout responsivi e complessi con poche righe di codice. In questo articolo esploreremo le sue funzionalità principali.",
        "tags": ["css"],
        "published": false,
    },
]
